;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Type.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Action.LeapSlam",DevComment="")
+GameplayTagList=(Tag="Ability.Type.Duration.LeapSlam",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.LeapSlam.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.LeapSlam.Land",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Ability.LeapSlam.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Ability.LeapSlam.Land",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Landed",DevComment="")

