import unreal,json
from pathlib import Path
registry=unreal.AssetRegistryHelpers.get_asset_registry()
options=unreal.AssetRegistryDependencyOptions(include_hard_package_references=True,include_soft_package_references=True)
dependencies=[str(n) for n in registry.get_dependencies('/Game/Combat/Projectiles/FX/NS_Archer_IceShot',options)]
assert not any(n.startswith('/CascadeToNiagaraConverter/') for n in dependencies)
helper_dependencies=[str(n) for n in registry.get_dependencies('/Game/Combat/Projectiles/FX/Modules/MakeQuatFromEuler',options)]
assert not any(n.startswith('/CascadeToNiagaraConverter/') for n in helper_dependencies)
report_path=Path(unreal.Paths.project_saved_dir(),'IceShotNiagaraVerification.json')
report=json.loads(report_path.read_text())
assert report['status']=='complete' and all(report['particle_counts'].values())
report['dependencies']=dependencies
report['helper_dependencies']=helper_dependencies
report_path.write_text(json.dumps(report,indent=2))
# Remove only the intermediate asset generated by this conversion session.
intermediate='/Game/Combat/Projectiles/FX/Reference/NS_Archer_IceShot_FirstPass'
if unreal.EditorAssetLibrary.does_asset_exist(intermediate):
 assert unreal.EditorAssetLibrary.delete_asset(intermediate)
unreal.log('ICE_SHOT_NIAGARA_FINALIZED')
